<?php

use Phinx\Seed\AbstractSeed;

class BooksSeeder extends AbstractSeed
{
    public function run(): void
    {
        $this->execute('TRUNCATE TABLE books');

        $books = [
            // Novela
            ['title' => 'Cien años de soledad', 'author' => 'Gabriel García Márquez', 'genre' => 'Novela', 'isbn' => '9780307474728', 'price' => 1850.00, 'stock' => 12, 'description' => 'Considerada una obra maestra de la literatura universal, esta inmensa saga familiar narra la historia de la estirpe de los Buendía a lo largo de siete generaciones en el mítico pueblo de Macondo. La novela entrelaza magistralmente el mito, la política y la fantasía mediante el realismo mágico, explorando el inevitable destino cíclico y la profunda soledad humana.'],
            ['title' => 'Don Quijote de la Mancha', 'author' => 'Miguel de Cervantes', 'genre' => 'Novela', 'isbn' => '9788424922580', 'price' => 2200.00, 'stock' => 5, 'description' => 'Obra cumbre de las letras hispanas que relata las tragicómicas aventuras del idealista Alonso Quijano y su pragmático escudero Sancho Panza. Nacida como una feroz sátira de los libros de caballerías, la novela se convierte en una profunda meditación sobre la frontera entre la cordura y la locura, la realidad y la ficción, en la España del Siglo de Oro.'],
            ['title' => 'La casa de los espíritus', 'author' => 'Isabel Allende', 'genre' => 'Novela', 'isbn' => '9780553383805', 'price' => 1700.00, 'stock' => 10, 'description' => 'Una cautivadora epopeya que traza la vida de la familia Trueba a lo largo del turbulento siglo XX en Chile. Liderada por el patriarca conservador Esteban y su esposa clarividente Clara, la novela combina tensiones de clase, conflictos políticos y el advenimiento de una dura dictadura militar con elementos sobrenaturales y un profundo linaje matriarcal.'],
            ['title' => 'El túnel', 'author' => 'Ernesto Sabato', 'genre' => 'Novela', 'isbn' => '9789500704823', 'price' => 950.00, 'stock' => 20, 'description' => 'Un asfixiante thriller psicológico narrado en primera persona por Juan Pablo Castel, un pintor que desde la cárcel confiesa el asesinato de María Iribarne, la única mujer que creyó comprenderlo. Sabato construye una exploración existencialista y cruda sobre la incomunicación, la paranoia, el aislamiento urbano y la absoluta soledad del individuo moderno.'],
            ['title' => 'Sobre héroes y tumbas', 'author' => 'Ernesto Sabato', 'genre' => 'Novela', 'isbn' => '9789500705820', 'price' => 1600.00, 'stock' => 7, 'description' => 'Pilar fundamental de la literatura argentina que entrelaza la trágica historia de amor entre Martín y la enigmática Alejandra Vidal Olmos con el oscuro e inquietante "Informe sobre ciegos". A través de sus múltiples capas, la obra indaga en la locura, las raíces de la decadencia nacional y los fantasmas del pasado histórico argentino.'],
            ['title' => 'Rayuela', 'author' => 'Julio Cortázar', 'genre' => 'Novela', 'isbn' => '9788466329583', 'price' => 1900.00, 'stock' => 11, 'description' => 'Un hito de la experimentación narrativa que revolucionó la literatura contemporánea. Siguiendo las andanzas del intelectual Horacio Oliveira y su fascinación por La Maga entre los puentes de París y las calles de Buenos Aires, el libro ofrece un "tablero de dirección" que permite al lector elegir múltiples caminos y saltar entre capítulos de forma lúdica.'],
            ['title' => 'La ciudad y los perros', 'author' => 'Mario Vargas Llosa', 'genre' => 'Novela', 'isbn' => '9788420648354', 'price' => 1750.00, 'stock' => 6, 'description' => 'Una contundente crítica a la brutalidad y el machismo institucionalizado, ambientada en el rígido Colegio Militar Leoncio Prado de Lima. A través de la dura convivencia de un grupo de cadetes, la obra desnuda la hipocresía social, la pérdida de la inocencia y las marcadas desigualdades que fracturan a la sociedad peruana.'],
            ['title' => 'Conversación en La Catedral', 'author' => 'Mario Vargas Llosa', 'genre' => 'Novela', 'isbn' => '9788420648378', 'price' => 2100.00, 'stock' => 4, 'description' => 'A partir del encuentro entre el periodista Zavalita y el ex chofer Ambrosio en el bar limeño "La Catedral", se despliega un monumental retrato del Perú bajo la sofocante dictadura de Manuel Odría. La novela intenta responder a la famosa pregunta de "cuándo se jodió el Perú", tejiendo redes de corrupción, cinismo y represión.'],
            ['title' => 'Pedro Páramo', 'author' => 'Juan Rulfo', 'genre' => 'Novela', 'isbn' => '9788437604183', 'price' => 1050.00, 'stock' => 18, 'description' => 'Juan Preciado viaja al árido y fantasmagórico pueblo de Comala para buscar a su padre, el despótico cacique Pedro Páramo. Lo que encuentra es un purgatorio de voces, murmullos y almas en pena que reconstruyen la historia de un pueblo devastado por el abuso de poder y la violencia, en una obra cumbre de la narrativa latinoamericana.'],
            ['title' => 'La vorágine', 'author' => 'José Eustasio Rivera', 'genre' => 'Novela', 'isbn' => '9789586147453', 'price' => 1300.00, 'stock' => 3, 'description' => 'A través de la voz del poeta Arturo Cova, la novela narra un descenso a los infiernos de la selva amazónica durante la despiadada "fiebre del caucho". Es a la vez un relato de aventuras desesperadas, un crudo enfrentamiento entre el hombre y una naturaleza indomable, y una férrea denuncia contra la explotación de los trabajadores indígenas.'],

            // Cuento
            ['title' => 'El Aleph', 'author' => 'Jorge Luis Borges', 'genre' => 'Cuento', 'isbn' => '9789500304801', 'price' => 1200.00, 'stock' => 8, 'description' => 'Una de las colecciones de cuentos más importantes del siglo XX. En sus páginas, Borges desentraña los grandes misterios del universo mediante relatos fascinantes sobre el infinito, la identidad, laberintos inabarcables, inmortales y un punto mítico en un sótano de Buenos Aires donde convergen todos los lugares y tiempos posibles.'],
            ['title' => 'Ficciones', 'author' => 'Jorge Luis Borges', 'genre' => 'Cuento', 'isbn' => '9788420633749', 'price' => 1350.00, 'stock' => 15, 'description' => 'Un volumen clave para entender la literatura fantástica. Dividido en "El jardín de senderos que se bifurcan" y "Artificios", recopila cuentos magistrales que reflexionan sobre bibliotecas infinitas, sectas secretas, enciclopedias de mundos apócrifos y la naturaleza engañosa de la memoria y la escritura literaria.'],
            ['title' => 'Final del juego', 'author' => 'Julio Cortázar', 'genre' => 'Cuento', 'isbn' => '9788466333054', 'price' => 1100.00, 'stock' => 9, 'description' => 'Dieciocho relatos que capturan el inconfundible estilo cortazariano, donde lo cotidiano se ve repentinamente fracturado por lo absurdo o lo fantástico. Incluye cuentos emblemáticos como "Continuidad de los parques" y "Axolotl", explorando las tensiones de la infancia, las obsesiones sutiles y las difusas fronteras de la realidad.'],
            ['title' => 'El llano en llamas', 'author' => 'Juan Rulfo', 'genre' => 'Cuento', 'isbn' => '9788437604190', 'price' => 900.00, 'stock' => 14, 'description' => 'Diecisiete relatos descarnados que retratan con una prosa seca y poética la crudeza de la vida rural en el estado de Jalisco, México. Tras los estragos de la Revolución y la Guerra Cristera, los personajes de Rulfo deambulan entre la fatalidad, la venganza, la sequía y la desolación de un paisaje implacable.'],
            ['title' => 'El jardín de los senderos que se bifurcan', 'author' => 'Jorge Luis Borges', 'genre' => 'Cuento', 'isbn' => '9789500304856', 'price' => 1300.00, 'stock' => 8, 'description' => 'El cuento que da título al famoso volumen es un intrincado relato de espionaje durante la Primera Guerra Mundial que esconde, en su núcleo, una compleja reflexión filosófica sobre el tiempo. Borges plantea la existencia de universos paralelos y realidades múltiples donde todas las opciones posibles ocurren simultáneamente.'],
            ['title' => 'Los cachorros', 'author' => 'Mario Vargas Llosa', 'genre' => 'Cuento', 'isbn' => '9788420650647', 'price' => 850.00, 'stock' => 11, 'description' => 'Una novela corta y vibrante que sigue la vida de Cuéllar y su grupo de amigos en el entorno acomodado del barrio de Miraflores. Tras sufrir un trágico y traumático accidente en su infancia, la narrativa explora con ritmo coral la frustración, la presión social para cumplir con los roles de género y el aislamiento que lo acompaña hasta la adultez.'],
            ['title' => 'El hacedor', 'author' => 'Jorge Luis Borges', 'genre' => 'Cuento', 'isbn' => '9789500304887', 'price' => 1050.00, 'stock' => 10, 'description' => 'Una colección íntima e híbrida que alterna entre la prosa y el verso. Escrito cuando la ceguera del autor comenzaba a ser definitiva, es un libro profundamente personal donde Borges dialoga con Homero, explora la figura del creador ciego, medita sobre sus obsesiones recurrentes y cuestiona la naturaleza misma de su identidad como escritor.'],
            ['title' => 'Historia universal de la infamia', 'author' => 'Jorge Luis Borges', 'genre' => 'Cuento', 'isbn' => '9789500304894', 'price' => 980.00, 'stock' => 11, 'description' => 'El primer libro de cuentos de Borges, donde toma biografías de personajes históricos reales —piratas, gánsteres, impostores y viudas negras— y las manipula libremente con su destreza literaria. Una serie de relatos dinámicos y estilizados que celebran el engaño, la maldad pintoresca y el puro placer de la ficción narrativa.'],
            ['title' => 'Las armas secretas', 'author' => 'Julio Cortázar', 'genre' => 'Cuento', 'isbn' => '9788466333061', 'price' => 1000.00, 'stock' => 9, 'description' => 'Una de las antologías más aclamadas del autor argentino, que marca una evolución hacia tramas más complejas y de mayor extensión. Contiene obras maestras absolutas del cuento hispanoamericano como "El perseguidor", "Las babas del diablo" y "Cartas de mamá", sumergiendo al lector en universos paralelos, la culpa y la percepción visual.'],
            ['title' => 'Bestiario', 'author' => 'Julio Cortázar', 'genre' => 'Cuento', 'isbn' => '9788466333078', 'price' => 950.00, 'stock' => 13, 'description' => 'El primer volumen de relatos que Cortázar publicó con su propio nombre. En estas historias magistrales, como "Casa tomada", "Carta a una señorita en París" y "Lejana", los personajes ven cómo su tranquilidad burguesa es subvertida abruptamente por lo inexplicable, los monstruos literales o las pesadillas que cobran vida propia.'],
            ['title' => 'Cuentos de amor de locura y de muerte', 'author' => 'Horacio Quiroga', 'genre' => 'Cuento', 'isbn' => '9789500706759', 'price' => 1000.00, 'stock' => 15, 'description' => 'Una compilación de relatos desgarradores fuertemente influenciados por Edgar Allan Poe. Quiroga traslada el terror psicológico al escenario salvaje de la selva misionera, donde la naturaleza se presenta como una fuerza hostil y letal. El libro indaga sin piedad en las debilidades humanas, las enfermedades súbitas y las tragedias pasionales.'],
            ['title' => 'La gallina degollada', 'author' => 'Horacio Quiroga', 'genre' => 'Cuento', 'isbn' => '9789500706766', 'price' => 850.00, 'stock' => 12, 'description' => 'Un relato escalofriante y de gran intensidad psicológica que expone el desgaste emocional del matrimonio Mazzini-Ferraz. Tras engendrar a cuatro hijos que caen presa de un misterioso retraso mental infantil, la pareja deposita toda su esperanza en una quinta hija sana, desencadenando un clímax marcado por la negligencia, la brutalidad y lo macabro.'],
            ['title' => 'El perseguidor', 'author' => 'Julio Cortázar', 'genre' => 'Cuento', 'isbn' => '9788466333108', 'price' => 900.00, 'stock' => 8, 'description' => 'Una de las piezas más profundas de Cortázar. Basado libremente en los últimos días del saxofonista Charlie Parker, el relato sigue a Johnny Carter a través de la mirada de su biógrafo, Bruno. Es una meditación existencial sobre el arte, el paso vertiginoso del tiempo y la autodestrucción inevitable de un genio musical en las calles de París.'],
            ['title' => 'Un tal Lucas', 'author' => 'Julio Cortázar', 'genre' => 'Cuento', 'isbn' => '9788466333122', 'price' => 1100.00, 'stock' => 7, 'description' => 'Una colección de viñetas breves, apuntes irónicos y divagaciones donde Cortázar presenta a su alter ego, Lucas. Rompiendo con la estructura narrativa convencional, el libro ofrece una mirada fresca, melancólica y profundamente humorística sobre situaciones cotidianas, hospitales, la vejez, los amigos y la excentricidad de la vida moderna.'],
            ['title' => 'Los funerales de la Mamá Grande', 'author' => 'Gabriel García Márquez', 'genre' => 'Cuento', 'isbn' => '9780307389763', 'price' => 1000.00, 'stock' => 11, 'description' => 'Libro de cuentos que consolida el universo literario de Macondo antes de "Cien años de soledad". A través del relato principal que da título al volumen, se narra la fastuosa y desproporcionada sepultura de la soberana absoluta del territorio, satirizando los caudillismos latinoamericanos con una prosa desbordante, mítica y llena de color.'],
            ['title' => 'La increíble y triste historia de la cándida Eréndira', 'author' => 'Gabriel García Márquez', 'genre' => 'Cuento', 'isbn' => '9780307389770', 'price' => 1050.00, 'stock' => 8, 'description' => 'Tras un incendio accidental que destruye su hogar, la adolescente Eréndira es obligada por su desalmada y colosal abuela a prostituirse por el desierto de la Guajira para pagar su deuda. Un relato cruel y a la vez poético que entremezcla contrabandistas, milagros ilusorios y la opresión en un viaje surrealista por la miseria del Caribe.'],
            ['title' => 'El exilio y el reino', 'author' => 'Albert Camus', 'genre' => 'Cuento', 'isbn' => '9788420633756', 'price' => 1300.00, 'stock' => 9, 'description' => 'Último libro de ficción publicado por Camus en vida. Compuesto por seis relatos ambientados desde el norte de África hasta Brasil, aborda el perpetuo dilema humano entre la alienación social (el exilio) y el sentido de pertenencia moral o fraternidad (el reino). Una obra imprescindible cargada de intensidad filosófica.'],

            // Poesía
            ['title' => 'Martín Fierro', 'author' => 'José Hernández', 'genre' => 'Poesía', 'isbn' => '9789500706704', 'price' => 800.00, 'stock' => 25, 'description' => 'El máximo exponente de la literatura gauchesca y poema nacional de Argentina. Dividido en "La ida" y "La vuelta", canta en octosílabos las desgracias de un gaucho trabajador y pacífico que, reclutado a la fuerza para defender las fronteras y víctima de la injusticia del sistema, se ve empujado a convertirse en un marginado y desertor.'],
            ['title' => 'Piedra de sol', 'author' => 'Octavio Paz', 'genre' => 'Poesía', 'isbn' => '9786071600790', 'price' => 900.00, 'stock' => 8, 'description' => 'Un extenso poema circular compuesto exactamente por 584 endecasílabos, correspondientes al ciclo orbital de Venus según el calendario azteca. Es una exploración lírica deslumbrante donde Paz reflexiona sobre la fuerza transgresora del amor, el fluir incesante del tiempo, la comunión erótica y el sentido último de la existencia humana.'],
            ['title' => 'Veinte poemas de amor y una canción desesperada', 'author' => 'Pablo Neruda', 'genre' => 'Poesía', 'isbn' => '9789681903275', 'price' => 850.00, 'stock' => 22, 'description' => 'Publicado cuando Neruda tenía apenas veinte años, este poemario se convirtió en uno de los libros más leídos en lengua española. Combina imágenes de la indomable naturaleza del sur de Chile con un erotismo vibrante, retratando la plenitud, la angustia del deseo, la nostalgia y el inevitable desgarro de la separación amorosa.'],
            ['title' => 'Canto general', 'author' => 'Pablo Neruda', 'genre' => 'Poesía', 'isbn' => '9789681903282', 'price' => 1600.00, 'stock' => 7, 'description' => 'La obra más ambiciosa del poeta chileno, estructurada como una inmensa epopeya coral. A través de miles de versos, Neruda reescribe la historia de América Latina desde sus orígenes geológicos y mitológicos, pasando por la conquista y las luchas independentistas, erigiéndose como un canto de denuncia política y hermandad continental.'],
            ['title' => 'Residencia en la tierra', 'author' => 'Pablo Neruda', 'genre' => 'Poesía', 'isbn' => '9789681903299', 'price' => 1200.00, 'stock' => 9, 'description' => 'Escrito en gran parte durante el aislamiento que sufrió como cónsul en Oriente, este libro marca la etapa más vanguardista, surrealista y hermética de Neruda. Sus poemas destilan una profunda visión pesimista, caracterizados por una atmósfera de desintegración, angustia existencial, materia en descomposición y el fluir destructivo del tiempo.'],
            ['title' => 'Poemas humanos', 'author' => 'César Vallejo', 'genre' => 'Poesía', 'isbn' => '9789507400155', 'price' => 1100.00, 'stock' => 10, 'description' => 'Publicados póstumamente gracias a la labor de su viuda, estos versos constituyen uno de los testimonios líricos más conmovedores sobre el dolor existencial. Vallejo abandona el experimentalismo extremo para abrazar una voz más cercana, solidaria y desgarrada, abordando la pobreza, la fragilidad corporal y el sufrimiento inherente a la condición humana.'],
            ['title' => 'Trilce', 'author' => 'César Vallejo', 'genre' => 'Poesía', 'isbn' => '9789507400162', 'price' => 950.00, 'stock' => 7, 'description' => 'Un estallido de vanguardia radical publicado en 1922 que dinamitó todas las convenciones métricas y sintácticas del momento. A través de neologismos, alteraciones ortográficas y quiebres lógicos, Vallejo creó un lenguaje poético inédito y visceral para expresar su asfixia vital, la orfandad y la dolorosa experiencia de estar en prisión.'],
            ['title' => 'Los heraldos negros', 'author' => 'César Vallejo', 'genre' => 'Poesía', 'isbn' => '9789507400179', 'price' => 1000.00, 'stock' => 8, 'description' => 'El debut literario de Vallejo, aún deudor del modernismo pero que ya prefigura su inconfundible voz sombría. Conocido universalmente por su poema homónimo ("Hay golpes en la vida, tan fuertes... ¡Yo no sé!"), el libro es un grito de rebelión ante un Dios ausente y una interrogación sobre el destino, la culpa y el sufrimiento inexplicable.'],
            ['title' => 'Altazor', 'author' => 'Vicente Huidobro', 'genre' => 'Poesía', 'isbn' => '9789561300286', 'price' => 950.00, 'stock' => 6, 'description' => 'Obra cumbre del Creacionismo. Estructurada en siete cantos, simula el vuelo en paracaídas del poeta "Altazor", un viaje en caída libre desde las alturas espirituales que se precipita hacia la descomposición semántica y sintáctica. Es una aventura fascinante donde el lenguaje mismo se quiebra, se deconstruye y se reinventa hasta llegar al puro sonido.'],
            ['title' => 'Azul', 'author' => 'Rubén Darío', 'genre' => 'Poesía', 'isbn' => '9789500706773', 'price' => 800.00, 'stock' => 11, 'description' => 'El libro que inauguró formalmente el Modernismo literario en la lengua española. A través de una exquisita mezcla de cuentos en prosa poética y poemas de métrica innovadora, el nicaragüense Darío nos transporta a mundos idealizados de cisnes, hadas y palacios, revolucionando por completo la musicalidad y estética de la época.'],
            ['title' => 'Prosas profanas', 'author' => 'Rubén Darío', 'genre' => 'Poesía', 'isbn' => '9789500706780', 'price' => 850.00, 'stock' => 9, 'description' => 'La obra que representa la madurez estilística del Modernismo. Aquí el poeta despliega toda su destreza técnica, introduciendo audacias rítmicas, motivos mitológicos, exotismo parisino e influencias del simbolismo francés. Celebra el esteticismo puro, el placer sensorial y el culto a la belleza formal como un refugio ante la vulgaridad.'],
            ['title' => 'Cantos de vida y esperanza', 'author' => 'Rubén Darío', 'genre' => 'Poesía', 'isbn' => '9789500706797', 'price' => 900.00, 'stock' => 8, 'description' => 'Un Darío más maduro, íntimo y preocupado por la realidad política marca este libro fundamental. Sin abandonar la belleza lírica, el poeta deja atrás el preciosismo extremo para dar paso a la reflexión angustiosa sobre la juventud perdida, el miedo a la muerte, su fe en la hispanidad y su advertencia contra el creciente imperialismo de Estados Unidos.'],

            // Ensayo
            ['title' => 'Facundo', 'author' => 'Domingo Faustino Sarmiento', 'genre' => 'Ensayo', 'isbn' => '9789500706728', 'price' => 1000.00, 'stock' => 13, 'description' => 'Subtitulado "Civilización y barbarie", es uno de los textos fundacionales más importantes de la literatura argentina. Mitad biografía del caudillo riojano Facundo Quiroga, mitad ensayo sociológico, Sarmiento disecciona la geografía pampeana y sus habitantes para explicar las guerras civiles de la época y argumentar a favor de la modernización europea.'],
            ['title' => 'El laberinto de la soledad', 'author' => 'Octavio Paz', 'genre' => 'Ensayo', 'isbn' => '9786071600783', 'price' => 1400.00, 'stock' => 14, 'description' => 'Un lúcido y penetrante análisis sobre la psique, la historia y la identidad del mexicano. Paz ahonda en el complejo de inferioridad, el machismo, la actitud estoica ante la muerte, el mestizaje conflictivo herencia de la Conquista y las máscaras sociales que utiliza su pueblo para ocultar una profunda e histórica soledad espiritual.'],
            ['title' => 'El escritor y sus fantasmas', 'author' => 'Ernesto Sabato', 'genre' => 'Ensayo', 'isbn' => '9789500705844', 'price' => 1100.00, 'stock' => 6, 'description' => 'Una recopilación de ensayos breves, aforismos y notas donde el autor argentino expone su ideario estético y filosófico. Sabato dialoga con otros grandes genios de la literatura universal para desmenuzar las motivaciones inconscientes, los tormentos, la responsabilidad ética y las crisis internas que impulsan y acompañan el acto creador.'],
            ['title' => 'Antes del fin', 'author' => 'Ernesto Sabato', 'genre' => 'Ensayo', 'isbn' => '9789500705851', 'price' => 950.00, 'stock' => 8, 'description' => 'Concebido como una especie de testamento espiritual publicado en el ocaso de su vida, Sabato entrelaza memorias de su juventud anarquista y su paso por la física con profundas reflexiones melancólicas. Un llamado a resistir en un mundo tecnocrático y materialista, aferrándose al arte, los afectos genuinos y la esperanza frente al abismo.'],
            ['title' => 'Formas breves', 'author' => 'Ricardo Piglia', 'genre' => 'Ensayo', 'isbn' => '9789500706841', 'price' => 1100.00, 'stock' => 8, 'description' => 'Un brillante acercamiento crítico donde el autor reflexiona sobre el oficio de leer y escribir. Mezclando el apunte personal, la teoría literaria y el estilo narrativo propio de sus ficciones, Piglia analiza a autores como Borges, Arlt, Macedonio Fernández y Poe, destilando iluminadoras tesis sobre la estructura oculta de los cuentos modernos.'],
            ['title' => 'Paula', 'author' => 'Isabel Allende', 'genre' => 'Ensayo', 'isbn' => '9780553562804', 'price' => 1350.00, 'stock' => 6, 'description' => 'Nacido como una extensa carta escrita en los pasillos de un hospital de Madrid, este conmovedor relato autobiográfico fue redactado mientras la hija de la autora caía en un coma irreversible debido a la porfiria. Allende entrelaza el inmenso dolor de la pérdida inminente con memorias vívidas de la historia familiar y el golpe militar chileno.'],
            ['title' => 'El mito de Sísifo', 'author' => 'Albert Camus', 'genre' => 'Ensayo', 'isbn' => '9788420633787', 'price' => 1000.00, 'stock' => 8, 'description' => 'Un ensayo filosófico crucial que introduce la teoría del absurdo existencial. Comparando a la humanidad con Sísifo —condenado por los dioses a empujar eternamente una roca cuesta arriba solo para verla caer—, Camus argumenta que, a pesar de que la vida carece de un sentido inmanente, uno debe imaginar a Sísifo feliz en el acto de la rebelión consciente.'],
            ['title' => 'El ser y la nada', 'author' => 'Jean-Paul Sartre', 'genre' => 'Ensayo', 'isbn' => '9788420633817', 'price' => 2300.00, 'stock' => 3, 'description' => 'El tratado fundacional del existencialismo francés moderno. En esta obra densa y monumental, Sartre expone sus ideas sobre la conciencia, la "mala fe", la mirada del Otro y el postulado de que "la existencia precede a la esencia". Reivindica la absoluta y abrumadora libertad humana, que condena a cada individuo a la responsabilidad total de sus actos.'],
            ['title' => 'Las palabras', 'author' => 'Jean-Paul Sartre', 'genre' => 'Ensayo', 'isbn' => '9788420633824', 'price' => 1100.00, 'stock' => 6, 'description' => 'Una obra maestra del género autobiográfico. Sartre despelleja con ironía y brillantez sus primeros diez años de vida en el seno de un hogar burgués, narrando cómo construyó su identidad engañosa alrededor de los libros, la lectura en el despacho de su abuelo y la imperiosa y pretenciosa vocación de convertirse en un genio literario.']
        ];

        $this->table('books')->insert($books)->saveData();
    }
}
